% (C) Copyright 2019 bidspm developers

clear;
clc;

% add spm
warning('off');
addpath(genpath('/Users/battal/Documents/MATLAB/spm12'));

% add bispm
this_dir = fileparts(mfilename('fullpath'));
bidspm_dir = fullfile(this_dir, '..', 'lib', 'bidspm');
addpath(bidspm_dir);
bidspm();

project_dir = fullfile(this_dir, '..', '..');

bids_dir = fullfile(project_dir, 'inputs', 'raw');
output_dir = fullfile(project_dir, 'outputs', 'derivatives');

mkdir(output_dir);

bidspm(bids_dir, output_dir, 'subject', ...
       'action', 'preprocess', ...
       'participant_label', {'ctrl012'}, ...
       'task', 'somatotopy', ...
       'space', {'individual', 'IXI549Space'},...
       'bids_filter_file', struct([]), ...
       'verbosity', 2, ...
       'options', struct([]), ...
       'dry_run', false, ...
       'dummy_scans', 0, ...
       'anat_only', false, ...
       'ignore', {}, ...
       'fwhm', 6, ...
       'skip_validation', false);
